var fs = require('fs');
var stream = fs.createWriteStream("data.txt");
const firstNames =  [ "Adam", "Alex", "Aaron", "Ben", "Carl", "Dan", "David", "Edward", "Fred", "Frank", "George", "Hal", "Hank", "Ike", "John", "Jack", "Joe", "Larry", "Monte", "Matthew", "Mark", "Nathan", "Otto", "Paul", "Peter", "Roger", "Roger", "Steve", "Thomas", "Tim", "Ty", "Victor", "Walter"];  

const lastNames = [ "Anderson", "Ashwoon", "Aikin", "Bateman", "Bongard", "Bowers", "Boyd", "Cannon", "Cast", "Deitz", "Dewalt", "Ebner", "Frick", "Hancock", "Haworth", "Hesch", "Hoffman", "Kassing", "Knutson", "Lawless", "Lawicki", "Mccord", "McCormack", "Miller", "Myers", "Nugent", "Ortiz", "Orwig", "Ory", "Paiser", "Pak", "Pettigrew", "Quinn", "Quizoz", "Ramachandran", "Resnick", "Sagar", "Schickowski", "Schiebel", "Sellon", "Severson", "Shaffer", "Solberg", "Soloman", "Sonderling", "Soukup", "Soulis", "Stahl", "Sweeney", "Tandy", "Trebil", "Trusela", "Trussel", "Turco", "Uddin", "Uflan", "Ulrich", "Upson", "Vader", "Vail", "Valente", "Van Zandt", "Vanderpoel", "Ventotla", "Vogal", "Wagle", "Wagner", "Wakefield", "Weinstein", "Weiss", "Woo", "Yang", "Yates", "Yocum", "Zeaser", "Zeller", "Ziegler", "Bauer", "Baxster", "Casal", "Cataldi", "Caswell", "Celedon", "Chambers", "Chapman", "Christensen", "Darnell", "Davidson", "Davis", "DeLorenzo", "Dinkins", "Doran", "Dugelman", "Dugan", "Duffman", "Eastman", "Ferro", "Ferry", "Fletcher", "Fietzer", "Hylan", "Hydinger", "Illingsworth", "Ingram", "Irwin", "Jagtap", "Jenson", "Johnson", "Johnsen", "Jones", "Jurgenson", "Kalleg", "Kaskel", "Keller", "Leisinger", "LePage", "Lewis", "Linde", "Lulloff", "Maki", "Martin", "McGinnis", "Mills", "Moody", "Moore", "Napier", "Nelson", "Norquist", "Nuttle", "Olson", "Ostrander", "Reamer", "Reardon", "Reyes", "Rice", "Ripka", "Roberts", "Rogers", "Root", "Sandstrom", "Sawyer", "Schlicht", "Schmitt", "Schwager", "Schutz", "Schuster", "Tapia", "Thompson", "Tiernan", "Tisler" ];

const genders = ['Female', 'Male', 'Other']

const years = [ 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009 ]

const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombi',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor (Timor Timur)',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia, The',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]
const languages = [
"Pashto", 
"Uzbek", 
"Turkmen", 
"Swedish", 
"Albanian", 
"Arabic", 
"English", 
"Samoan", 
"Catalan", 
"Portuguese", 
"Russian", 
"Spanish", 
"Guaraní", 
"Armenian", 
"Dutch", 
"(Eastern) Punjabi", 
"German", 
"Azerbaijani", 
"Bengali", 
"Belarusian", 
"French", 
"Dzongkha", 
"Aymara", 
"Quechua", 
"Bosnian", 
"Croatian", 
"Serbian", 
"Tswana", 
"Norwegian", 
"Norwegian Bokmål", 
"Norwegian Nynorsk", 
"Malay", 
"Bulgarian", 
"Fula", 
"Kirundi", 
"Khmer", 
"Sango", 
"Chinese", 
"Lingala", 
"Kongo", 
"Swahili", 
"Luba-Katanga", 
"Greek (modern)", 
"Turkish", 
"Czech", 
"Slovak", 
"Danish", 
"Tigrinya", 
"Estonian", 
"Amharic", 
"Faroese", 
"Fijian", 
"Hindi", 
"Urdu", 
"Finnish", 
"Georgian", 
"Kalaallisut", 
"Chamorro", 
"Haitian", 
"Latin", 
"Italian", 
"Hungarian", 
"Icelandic", 
"Indonesian", 
"Persian (Farsi)", 
"Kurdish", 
"Irish", 
"Manx", 
"Hebrew (modern)", 
"Japanese", 
"Kazakh", 
"Kyrgyz", 
"Lao", 
"Latvian", 
"Southern Sotho", 
"Lithuanian", 
"Luxembourgish", 
"Macedonian", 
"Malagasy", 
"Chichewa", 
"Malaysian", 
"Divehi", 
"Maltese", 
"Marshallese", 
"Romanian", 
"Mongolian", 
"Burmese", 
"Afrikaans", 
"Nauruan", 
"Nepali", 
"Māori", 
"Korean", 
"Polish", 
"Kinyarwanda", 
"Tamil", 
"Slovene", 
"Somali", 
"Southern Ndebele", 
"Swati", 
"Tsonga", 
"Venda", 
"Xhosa", 
"Zulu", 
"Sinhalese", 
"Tajik", 
"Thai", 
"Tonga (Tonga Islands)", 
"Ukrainian", 
"Bislama", 
"Vietnamese", 
"Shona", 
"Northern Ndebele"
]
const jobs = [
'.net developer',
'.net software developer',
'accessibility outreach coordinator',
'accessibility program manager',
'account executive ',
'account manager',
'accountable manager',
'accountable project manager',
'accountant',
'accounting investment analyst',
'actor',
'actuary',
'admin engineer',
'administrative aide',
'administrative assistant',
'administrative associate to the executive director',
'administrative business promotion coordinator',
'administrative claim examiner',
'administrative contract specialist',
'administrative coordinator',
'administrative engineer',
'administrative management auditor',
'administrative manager',
'administrative office assistant',
'administrative procurement analyst',
'administrative services manager',
'administrative specialist',
'administrative staff analyst',
'administrative support',
'administrative transportation coordinator',
'administrator on duty',
'advertising and promotions manager',
'advertising sales agent',
'aerospace engineer',
'agency attorney',
'agency counsel',
'agricultural engineer',
'agricultural scientist',
'agricultural technician',
'aide',
'air & noise pollution inspector',
'aircraft mechanic',
'aircraft pilot',
'analyst manager',
'analyst',
'animal caretaker',
'animal control worker',
'animal trainer',
'animalbreeder',
'announcer',
'apparel patternmaker',
'appliance repairer',
'application developer',
'application examiner',
'application solution manager',
'application support analyst',
'application support reporting specialist',
'application worker',
'appraiser',
'apprentice inspector',
'architect',
'architectural designer',
'archivist',
'artist',
'assembler',
'assessor ',
'asset management specialist',
'asset manager',
'assistant architect',
'assistant business services associate',
'assistant chief of facility compliance',
'assistant civil engineer',
'assistant commissioner of administration',
'assistant commissioner of communications and policy',
'assistant commissioner of enforcement',
'assistant commissioner of environmental health unit',
'assistant commissioner of housing policy',
'assistant commissioner of the office of placement administration',
'assistant commissioner',
'assistant quality assurance associate',
'astronomer',
'atmospheric scientist',
'audiologist',
'audit engineer',
'audit intern',
'audit manager',
'audit supervisor',
'auditor',
'author',
'auto  machinist',
'auto mechanic',
'automotive glass installer',
'avionics technician',
'back end developer',
'baggage porter',
'bailiff',
'baker',
'barber',
'bartender helper',
'bartender',
'bellhop',
'best practices coach',
'bid operations liaison',
'bill and account collector',
'billing and posting clerk',
'biological scientist',
'biological technician',
'biomedical engineer',
'blake fellow',
'blockmason',
'boat captain',
'boiler inspector',
'boilermaker',
'bookbinder',
'bookkeeper',
'branch chief',
'brickmason',
'bridge operator',
'broadcast and sound engineering technician',
'brokerage clerk',
'budget analyst',
'budget review specialist',
'budget',
'building cleaner',
'building inspector',
'bus and truck mechanics and diesel engine specialist',
'business administrator ',
'business analyst',
'business intelligence developer',
'business manager',
'business operations specialist',
'business solution architect',
'butcher',
'buyer services manager',
'buyer',
'cabinetmaker',
'cafeteria attendant',
'calendar assistant',
'call center manager',
'camera operator',
'capacity building assistance specialist',
'cargo and freight agent',
'carpenter',
'cartographer',
'case analyst',
'case management nurse',
'case management team leader',
'case management unit supervisor',
'case monitor supervisor',
'case worker',
'cashier supervisor',
'cashier',
'caster',
'ceiling tile installer',
'cement mason',
'certified it administrator',
'certified it developer',
'certified specialist',
'channel manager',
'chauffeur',
'chef',
'chemical engineer',
'chemical technician',
'chemists',
'chief architect',
'chief compliance officer',
'chief diversity officer',
'chief engineer of dispute resolutions',
'chief executive',
'chief financial officer',
'chief information security officer',
'chief investigator',
'chief of staff',
'chief operating officer',
'chief plan examiner',
'chief review officer',
'child care worker',
'child welfare analyst',
'chiropractor',
'choreographer',
'city assessor',
'city laborer',
'city medical examiner',
'city park worker',
'city planner',
'city planning technician',
'city research scientist',
'civil design lead',
'civil engineer',
'civilian investigator',
'claim specialist',
'claims adjuster',
'claims processor',
'claims specialist',
'clergy',
'clerical aide',
'clerical assistant',
'clerical associate',
'clerical supervisor',
'clerk',
'client services representative',
'climber & pruner',
'clinical case supervisor',
'clinical director',
'clinical laboratory technologist and technician',
'cloud reliability engineer',
'coach',
'collections administrator',
'collector',
'college aide',
'commercial diver',
'communication electrician',
'communication manager',
'communication specialist',
'communication worker',
'communications equipment operator',
'community & industry relations associate',
'community assistant',
'community associate',
'community coordinator',
'community service manager',
'community supervisor',
'compliance analyst',
'compliance and enforcement attorney',
'compliance auditor',
'compliance manager',
'compliance officer',
'compliance support specialist',
'computer aide',
'computer and information systems manager',
'computer associate',
'computer control operator',
'computer hardware engineer',
'computer operator',
'computer programmer',
'computer scientist',
'computer service technician',
'computer software engineer',
'computer specialist',
'computer support specialist',
'computer systems manager',
'concierge',
'confidential investigator',
'conflict resolution specialist',
'consent specialist',
'conservation scientist ',
'constituent services liaison',
'construction inspector',
'construction intern',
'construction manager',
'construction project manager',
'construction safety and quality inspector',
'content developer',
'content engineer ',
'contract analyst',
'contract manager',
'contract processor',
'contract specialist',
'contracts attorney',
'contracts officer',
'conveyor operator',
'coordinator',
'correctional officer',
'correctional officers',
'cosmetologist',
'cost estimating manager',
'cost estimator',
'counselor',
'courier',
'court liaison officer',
'court representative',
'cranes & derricks inspector',
'credit analyst',
'credit authorizer',
'crime analyst',
'criminal investigator',
'criminalist',
'crm developer',
'crossing guard',
'cultural affairs coordinator',
'curator',
'custodial assistant',
'custodian',
'customer service & operations analysis intern',
'customer service representative',
'customer service',
'cybersecurity operations analyst',
'dam safety coordinator',
'dancer',
'data analyst',
'data and process analyst',
'data and technology analyst',
'data architect',
'data assistant',
'data engineer',
'data entry clerk',
'data entry keyer',
'data management assistant',
'data manager',
'data research analyst',
'data research specialist',
'data scientist',
'data support analyst',
'data warehouse architect',
'database administrator',
'database administrator',
'database developer',
'dba engineer',
'dba lead',
'deckhand',
'demonstrator',
'dental assistant',
'dental hygienist',
'dentist',
'deputy budget director',
'deputy chief engineer',
'deputy chief of outside development',
'deputy chief of quality assurance',
'deputy chief',
'deputy commissioner',
'deputy director',
'deputy executive director',
'derrick service unit operator',
'design manager',
'designer',
'desk clerk',
'desktop publisher',
'detectives',
'dietitian',
'director',
'dishwasher',
'dispatcher',
'distributor',
'division chief',
'door-to-door sales worker',
'drafter',
'dressmaker',
'drywall installer',
'dynamic crm developer',
'early childhood education consultant',
'early intervention official',
'earth driller',
'economic analyst',
'economist',
'edge engineer',
'e-discovery analyst',
'editor',
'editorial intern',
'education administrator',
'e-learning content developer',
'electrical engineer',
'electrical inspector',
'electrical power-line installer',
'electrician',
'electronics engineer',
'elementary teacher',
'elevator installer',
'elevator repairer',
'eligibility interviewer',
'eligibility worker',
'emergency communications specialist',
'emergency field logistics coordinator',
'emergency manager',
'emergency medical technician',
'employee benefits coordinator',
'employee relations specialist',
'energy analyst',
'energy policy advisor',
'energy program analyst',
'engineer in charge',
'engineering manager',
'engineering technician',
'engraver',
'entertainer',
'enviromental assessment coordinator',
'environmental compliance specialist',
'environmental engineer',
'environmental health & safety auditor',
'environmental health & safety incident investigator',
'environmental health & safety regional manager',
'environmental program manager',
'environmental project manager',
'environmental review unit',
'environmental scientist',
'environmental specialist',
'equipment training coordinator',
'equity & special projects coordinator',
'escalation line team leader',
'etchers',
'etl developer',
'etl lead',
'evaluation coordinator',
'evaluation lead',
'evaluation specialist',
'examiner',
'examining attorney',
'executive agency counsel',
'executive assistant',
'executive director',
'executive program coordinator',
'executive project auditor',
'executive project manager',
'explosives worker',
'extraction worker',
'facilities clerk',
'facilities management assistant',
'facility operations custodial assistant',
'family advocate',
'farm ranch and other agricultural manager',
'farmer ',
'fence erector',
'field  doctor',
'field captain',
'field inspector',
'field operations training coordinator',
'field outreach specialist',
'field services technician',
'field tech',
'field/desktop technician',
'file clerk',
'financial analyst',
'financial examiner',
'financial manager',
'financial reviewer',
'financial specialist',
'fingerprint unit specialist',
'fire fighter',
'fire inspector',
'fire medical officer',
'fiscal coordinator',
'fiscal manager',
'fish and game warden',
'fisher',
'fleet administrator',
'fleet assistant',
'fleet management assistant',
'flight engineer',
'food preparation worker',
'food science technician',
'food scientist',
'food server',
'food service manager',
'forensic logistics specialist',
'forensic pathology technician',
'forester',
'foster care program evaluator',
'front end developer',
'functional analyst',
'funeral director',
'funeral service worker',
'furniture coordinator',
'furniture finisher',
'gaming manager',
'gaming surveillance officer',
'gardener',
'general counsel',
'general manager ',
'general services associate',
'geological engineer',
'geological technician ',
'geologist',
'geoscientist',
'gis analyst',
'gis editor',
'gis specialist',
'glazier',
'grader',
'grant coordinator',
'grant manager',
'grant project manager',
'graphic artist',
'green infrastructure engineer',
'greeter',
'grounds maintenance worker',
'groundskeeping worker',
'group head',
'hairdresser',
'hairstylist',
'hazardous materials removal worker',
'head cook',
'health adviser',
'health diagnosing and treating practitioner',
'health navigator',
'health promoter',
'hearing officer',
'heat coordinator',
'heating plant technician',
'heavy vehicle and mobile equipment service technician',
'help desk representative',
'help desk technician',
'helper',
'high pressure plant tender',
'highway maintenance worker',
'highways and sewers inspector',
'hiring plan analyst',
'home health aide',
'homeowner mortgage service manager',
'host',
'hostess',
'hostler',
'housekeeping cleaner',
'hr payroll systems security architect',
'hr specialist',
'hro application support manager',
'human resources administrative assistant',
'human resources analyst',
'human resources assistant',
'human resources associate',
'human resources college aide',
'human resources coordinator',
'human resources generalist',
'human resources manager',
'human resources specialist',
'human resources support staff',
'human resources',
'human rights specialist',
'hunter',
'HVAC mechanic',
'implementation coordinator',
'incident commander',
'industrial control technician',
'industrial engineer',
'industrial hygienist',
'industrial production manager',
'industrial program compliance analyst',
'information clerk',
'information representative',
'information security architecture & engineering manager',
'information security audit and compliance manager',
'information security identity & access manager',
'information security officer',
'information systems and quality analyst',
'inspector general',
'inspector',
'inspector ',
'instructor',
'instrumentation specialist',
'insulation worker',
'insurance claims and policy processing clerk',
'insurance sales agent',
'insurance underwriter',
'intake investigator',
'integration support engineer',
'integrity control officer',
'interagency exercise coordinator',
'intergovernmental affairs intern',
'intergovernmental outreach coordinator',
'intergovernmental relations task force',
'intern',
'interpreter',
'interviewer',
'investigative auditor',
'investigative consultant',
'investigative manager',
'investigator trainee',
'investigator',
'investment analyst',
'investment officer',
'ios developer',
'ip telephony design engineer',
'iron worker',
'it - project manager',
'it auditor',
'it budget & contracts manager',
'it business analyst',
'it contract analyst',
'it contracts specialist',
'it helpdesk manager',
'it infrastructure project manager',
'it operations clerk',
'it relationship manager',
'it security analyst',
'it security officer',
'it support technician',
'jailer',
'janitor',
'janitorial worker',
'java developer',
'jeweler',
'judge',
'junior accountant',
'junior financial planning and reporting analyst',
'junior public health nurse',
'junior z/os engineer',
'juvenile implementation manager',
'juvenile justice trainer',
'kettle operator',
'kiln operator',
'kindergarten teacher',
'labor law investigator',
'labor relations attorney',
'labor relations specialist',
'labor standards investigator',
'laboratory associate',
'laboratory microbiologist',
'laboratory technician',
'landscape architect',
'lead business analyst',
'lead design engineer',
'lead designer',
'lead expense management analyst',
'lead trainer',
'learning management',
'lease analyst',
'leather workers',
'legal assistant',
'legal coordinator',
'legal support worker',
'legislator',
'letterer and sign painter',
'liaison',
'librarian',
'library assistant',
'library technician',
'licensed vocational nurse',
'licensing clerk',
'lifeguard',
'linux administrator',
'load officer',
'loan counselor',
'loan officer',
'lobby attendant',
'locksmith',
'locomotive engineer',
'lodging manager',
'logging worker',
'logistician',
'low pressure boiler inspector',
'machine operator',
'machinist',
'magistrate',
'maid',
'mail clerk',
'mail machine operator',
'mail superintendent',
'mailroom control clerk',
'mailroom section supervisor',
'maintenance facilitator',
'maintenance worker',
'management analyst',
'management auditor',
'management systems specialistcrm information systems manager',
'manager',
'mapping technician',
'marine electronics technician',
'marine engineer',
'marine oilermate',
'market researcher',
'marketing and sales manager',
'massage therapist',
'material moving worker',
'materials engineer',
'materials scientist',
'mathematician',
'measurer',
'mechanical cost estimator',
'mechanical engineer',
'media worker',
'mediation coordinator',
'medical and health services manager',
'medical assistant',
'medical examiner assistant',
'medical records and health information technician',
'medical scientist',
'medical technician',
'medicolegal analyst',
'medicolegal investigator',
'meeting and convention planner',
'mental health coordinator',
'messenger',
'metal work mechanic',
'meter reader',
'metrics and reporting engineer',
'middle school teacher',
'millwright',
'mining engineer',
'mining machine operator',
'mobile device management architect',
'molder',
'motor vehicle operator',
'museum technician',
'musician',
'natural sciences manager',
'naval architect',
'neigborhood resiliency specialist',
'network administrator',
'network engineer',
'network field technician',
'network services manager',
'news analyst',
'news and street vendor',
'nuclear engineer',
'nuclear technicians',
'nurse home visitor',
'nursing supervisor',
'nutrition consultant',
'nutritionist',
'occupational therapist assistant',
'occupational therapist',
'office administrator',
'office assistant',
'office clerk',
'office coordinator',
'office machine aide',
'office machine repairer',
'office manager',
'oil burner specialist',
'ombudsperson',
'on-line medical control physician',
'open data lead analyst',
'open market order coordinator',
'operations associate',
'operations coordinator',
'operations customer service liaison',
'operations desktop support technician',
'operations manager',
'optical network engineer',
'optician',
'optometrist',
'order clerk',
'order filler',
'ordered deductions analyst',
'ordnance handling expert',
'outbreak data analyst',
'outreach assistant',
'outreach intern',
'packager',
'packer',
'painter',
'paperhanger',
'paralegal aide',
'paralegal assistant supervisor',
'paralegal',
'paramedic',
'parking enforcement officer',
'parking enforcement worker',
'parking lot attendant',
'parks enforcement patrol',
'parts salesperson',
'patternmaker',
'payment analyst',
'payroll data associate',
'payroll liaison',
'payroll supervisor',
'payroll systems analyst',
'penalty processing unit cashier',
'peoplesoft developer',
'performance management specialist',
'performer',
'permit records assistant',
'personal and home care aide',
'personal care and service worker',
'personal financial advisor',
'personnel associate',
'personnel coordinator',
'pest control aide',
'pest control worker',
'petroleum engineer',
'petroleum technician',
'pharmacist',
'photogrammetrist',
'photographer',
'physical scientist',
'physical therapist assistant',
'physical therapist',
'physician assistant',
'physician',
'physicist',
'pile-driver operator',
'pipefitter',
'pipelayer',
'placement staff nurse',
'plan examiner',
'plan management specialist',
'plasterer',
'plumber',
'plumber\'s helper',
'plumbing and fire suppression engineer',
'plumbing inspector',
'podiatrist',
'police administrative aide',
'police officer',
'police surgeon',
'policeman',
'policy advisor',
'policy analyst',
'policy writer',
'port marine engineer',
'portal support engineer',
'portfolio manager',
'postal office clerk',
'postal service clerk',
'postal service mail carrier',
'postal service mail sorter',
'postmaster',
'postsecondary teacher',
'power plant operator',
'preplacement nurse practitioner',
'prepress technician',
'preschool teacher',
'press officer',
'presser',
'principal administrative associate',
'principle design manager',
'private detective',
'probation assistant',
'probation officer trainee',
'probation officer',
'procedural justice coordinator',
'process messenger',
'process reform analyst intern',
'process server',
'processor',
'procurement analyst',
'procurement clerk',
'procurement contracting officer',
'procurement specialist',
'producer ',
'product advisor',
'product manager',
'product owner',
'product promoter',
'product support specialist',
'production support',
'program administrator',
'program analyst',
'program and policy specialist',
'program assistant',
'program associate',
'program contract analyst',
'program coordinator for early childhood health',
'program executive',
'program management office assistant',
'program manager',
'program managercadd coordinator',
'program planner',
'program specialist',
'project coordinator',
'project cost estimator',
'project development coordinator',
'project director',
'project manager',
'project manager ',
'project planner',
'project specialist',
'projects coordinator',
'property acquisition coordinator',
'property manager',
'prosecutor',
'psychologist',
'public health adviser',
'public health assistant',
'public health detailing specialist',
'public health epidemiologist',
'public health nurse',
'public policy and training coordinator',
'public records aide',
'public relations manager',
'public relations specialist',
'public warning specialist',
'pumping station operator',
'purchasing agent - buyer',
'purchasing agent',
'purchasing manager',
'qa analyst',
'qa senior auditor',
'quality assurance auditor',
'quality assurance engineer',
'quality assurance manager',
'quality assurance project manager',
'quality assurance specialist',
'quality child care manager',
'quality control case reviewer',
'quality control senior engineer',
'quality improvement specialist',
'quality management specialist',
'radiation emergency response specialist',
'radiation therapist',
'radio and telecommunications equipment installer',
'radio operators',
'radio repair mechanic',
'radio room operator',
'railroad conductor',
'rail-track laying and maintenance equipment operator',
'rancher',
'real estate broker',
'real estate manager',
'rebar workers',
'receivables/payables analyst',
'receptionist',
'records officer',
'records searcher',
'recreation and fitness worker',
'recreational therapist',
'recruiting & onboarding coordinator',
'recruitment assistant',
'refuse and recyclable material collector',
'regional field administrative assistant',
'registered dental hygienist',
'registered nurse',
'regulatory and licensing specialist',
'regulatory compliance agency attorney',
'reinforcing iron worker',
'religious worker',
'remote learning team specialist',
'rental clerk',
'reporter',
'research analyst',
'research assistant',
'research scientist',
'resident engineer',
'residential advisor',
'resiliency coordinator',
'resiliency engineer',
'resource specialist',
'respiratory therapist',
'retail buyer',
'retail salesperson',
'retail specialist',
'revenue agent',
'revenue assistant',
'review unit supervisor',
'rezoning manager',
'rigger',
'risk management',
'roof bolter',
'roofer',
'roustabout',
'safe event coordinator',
'safety & equipment training specialist',
'safety accident investigator',
'safety auditor',
'safety engineer',
'sailor',
'sales agent',
'sales engineer',
'sales representative',
'samplers',
'sanitation engineer',
'scanning operator',
'school health nurse practitioner',
'school mental health consultant',
'school mental health training coordinator',
'scientistscientist',
'searcher',
'seasonal city park worker',
'secondary school teacher',
'secretary to division chief',
'section chief',
'securities commodities and financial services sales agent',
'security administrator',
'security and fire alarm systems installer',
'security guard',
'security officer',
'security specialist',
'security system administrator',
'security systems engineer',
'senior accountant',
'senior advisor',
'senior analyst',
'senior application engineer',
'senior architect cloud infrastructure design and engineering',
'senior bi developer',
'senior budget analyst',
'senior business analyst',
'senior case support associate',
'senior civil service advisor',
'senior construction manager',
'senior cook',
'senior counsel',
'senior crm developer',
'senior data analyst',
'senior data scientist',
'senior design engineer',
'senior developer',
'senior director it',
'senior director',
'senior early childhood education consultant',
'senior electrical engineer',
'senior engineer',
'senior estimator',
'senior exchange engineer',
'senior field supervisor',
'senior financial reporting investment analyst',
'senior forester for restitution',
'senior general counsel',
'senior human capital partnership and performance management analyst',
'senior human resources specialist',
'senior inspector',
'senior intergroup relations officer',
'senior investigative auditor',
'senior investment analyst',
'senior it business analyst',
'senior it project manager',
'senior landscape architect',
'senior mainframe programmer analyst',
'senior mobile developer',
'senior network engineer',
'senior network specialist',
'senior operations associate',
'senior organizational development and training specialist',
'senior payment analyst',
'senior peoplesoft analyst',
'senior police administrative aide',
'senior policy advisor',
'senior port engineer',
'senior product manager',
'senior program manager',
'senior program officer',
'senior programmer',
'senior project analyst',
'senior project controls specialist',
'senior project engineer',
'senior project leader',
'senior project manager',
'senior project officer',
'senior public health inspector',
'senior quality oversight analyst',
'senior rackets investigator',
'senior radio system network engineer',
'senior research analyst',
'senior resiliency planner',
'senior safety accident investigator',
'senior security analyst',
'senior service desk agent',
'senior staff electrical engineer',
'senior stationary engineer',
'senior technology analyst/coordinator',
'senior title examiner',
'senior trainer',
'senior urban designer',
'senior windows administrator',
'septic tank servicer',
'sergeant',
'server support engineer',
'service asset configuration manager',
'service contract procurement analyst',
'service desk agent',
'service desk manager',
'service station attendant',
'sewer pipe cleaner',
'sewer',
'sewing machine operator',
'sharepoint developer',
'sheet metal worker',
'sheriff\'s patrol officer',
'ship engineer',
'ship loaders',
'shuttle car operator',
'singer',
'small engine mechanic',
'social science research assistant',
'social scientist',
'social service specialist',
'social worker',
'sociologist',
'software developer',
'solar energy project manager',
'solutions director',
'sorter',
'space analyst',
'space scientists',
'special assistant to assistant deputy commissioner',
'special assistant',
'special consultant',
'special education teacher',
'special examiner',
'special projects manager',
'special underwriting project manager',
'speech-language pathologist',
'spending analyst',
'sql/oracle database administrator',
'sr. analyst',
'sr. internal auditor',
'staff analyst 2',
'staff analyst ii',
'staff analyst level ii',
'staff analyst',
'staff attorney',
'staff auditor',
'staff counsel',
'staff engineer / architect',
'staff photographer',
'standards specialist',
'stationary engineer',
'statistical analyst',
'statistical assistant',
'statistician',
'steamfitter',
'steel workers',
'stock clerk',
'stock worker level ii',
'stonemason',
'storage engineer',
'stormwater program coordinator',
'strategic account manager',
'strategic initiatives coordinator',
'strategic operations policy analyst',
'strategic partnership liaison',
'strategic planning associate',
'street ambassador',
'structural engineer',
'structural iron and steel worker',
'stucco mason',
'student data analyst',
'student legal specialist',
'summer college intern',
'summer communications assistant',
'summer graduate intern',
'summer it intern',
'supervising health nurse',
'supervising housing groundskeeper',
'supervising nurse',
'supervising physician',
'supervising public health advisor',
'supervisor',
'support engineer',
'support worker',
'surgeon',
'survey researcher',
'surveyor',
'switchboard operator',
'system administrator',
'systems access management engineer',
'systems administrator - computer software',
'systems analyst',
'tailor',
'talent acquisition specialist',
'taper',
'tax examiner',
'tax incentives director',
'tax preparer',
'taxi driver',
'teacher assistant',
'team coach team leader',
'technical investigator',
'technical lead',
'technical project manager/product owner',
'technical sales manager',
'technical solutions professional',
'technical writer',
'technician',
'telecommunications associate',
'telemarketer',
'telephone operator',
'teller',
'temporary assistant urban designer',
'temporary painter',
'tender',
'testifier/searcher',
'testing lead',
'therapist',
'thermostat repairer',
'third party services analyst',
'threat analysttimekeeper',
'ticket taker',
'tile installer',
'timekeeper',
'timekeeping specialist',
'tool grinder',
'tort attorney',
'tour guide',
'tracking and monitoring data analyst',
'trainer & curriculum development specialist',
'trainer',
'training specialists',
'transit and railroad policeman',
'translator',
'transportation specialist',
'transportation storage and distribution manager',
'trapper',
'trauma-informed early care and education case supervisor',
'travel agent',
'travel guide',
'triage coordinator',
'triage nurse',
'triage supervisor',
'trial preparation assistant',
'truck driver',
'typist',
'umpire',
'unit clerk',
'unit manager',
'unix system administrator',
'unix/linux systems lead',
'upholsterer',
'urban and regional planner',
'urban technology architect',
'urban technology security researcher',
'usher',
'valve installer',
'vessel construction manager',
'veterinarian',
'virtual systems engineer',
'vision screening assistant',
'vp for project management',
'wage subsidy processing clerk',
'waiter',
'waitress',
'water resources analyst',
'water use inspector',
'waterfront facilities engineer',
'waterfront project manager',
'watershed maintainer',
'web application developer',
'webform team member',
'weigher',
'welder',
'wellness advocate supervisor',
'wellness advocate',
'windows administrator',
'wireless coordinator',
'woodworker',
'word processor ',
'workforce management analyst',
'workforce planning intern',
'writer',
'x-ray technician',
'yardmaster',
'youth initiatives lead advisor',
] 
const maritalStatus =  [ 'Married', 'Single', 'Divorced', 'Widowed' ] 

let gName = (firstName, lastName) => {
   return firstName[Math.floor(Math.random() * firstName.length)] + ' ' + lastName[Math.floor(Math.random() * lastName.length)];  
}
let gGender = (genders) => {
   return genders[Math.floor(Math.random() * genders.length)]; 
}
let gYear = () => Math.floor(Math.random() * 90 + 1930)
let gMaritalStatus = (martalStatus) => maritalStatus[Math.floor(Math.random() * maritalStatus.length)]
let gCountries  = (countries) => countries[Math.floor(Math.random() * countries.length)]
let gLanguage = (languages) => languages[Math.floor(Math.random() * languages.length)]
let gJob = (jobs) => jobs[Math.floor(Math.random() * jobs.length)]
let gPhoneNumber = () => {
    let phoneNumber = '+'
    const phoneCodes = [
'44' ,
	'1' ,
	'213' ,
	'376' ,
	'244' ,
	'1264' ,
	'1268' ,
	'54' ,
	'374' ,
	'297' ,
	'61' ,
	'43' ,
	'994' ,
	'1242' ,
	'973' ,
	'880' ,
	'1246' ,
	'375' ,
	'32' ,
	'501' ,
	'229' ,
	'1441' ,
	'975' ,
	'591' ,
	'387' ,
	'267' ,
	'55' ,
	'673' ,
	'359' ,
	'226' ,
	'257' ,
	'855' ,
	'237' ,
	'1' ,
	'238' ,
	'1345' ,
	'236' ,
	'56' ,
	'86' ,
	'57' ,
	'269' ,
	'242' ,
	'682' ,
	'506' ,
	'385' ,
	'53' ,
	'90392' ,
	'357' ,
	'42' ,
	'45' ,
	'253' ,
	'1809' ,
	'1809' ,
	'593' ,
	'20' ,
	'503' ,
	'240' ,
	'291' ,
	'372' ,
	'251' ,
	'500' ,
	'298' ,
	'679' ,
	'358' ,
	'33' ,
	'594' ,
	'689' ,
	'241' ,
	'220' ,
	'7880' ,
	'49' ,
	'233' ,
	'350' ,
	'30' ,
	'299' ,
	'1473' ,
	'590' ,
	'671' ,
	'502' ,
	'224' ,
	'245' ,
	'592' ,
	'509' ,
	'504' ,
	'852' ,
	'36' ,
	'354' ,
	'91' ,
	'62' ,
	'98' ,
	'964' ,
	'353' ,
	'972' ,
	'39' ,
	'1876' ,
	'81' ,
	'962' ,
	'7' ,
	'254' ,
	'686' ,
	'850' ,
	'82' ,
	'965' ,
	'996' ,
	'856' ,
	'371' ,
	'961' ,
	'266' ,
	'231' ,
	'218' ,
	'417' ,
	'370' ,
	'352' ,
	'853' ,
	'389' ,
	'261' ,
	'265' ,
	'60' ,
	'960' ,
	'223' ,
	'356' ,
	'692' ,
	'596' ,
	'222' ,
	'269' ,
	'52' ,
	'691' ,
	'373' ,
	'377' ,
	'976' ,
	'1664' ,
	'212' ,
	'258' ,
	'95' ,
	'264' ,
	'674' ,
	'977' ,
	'31' ,
	'687' ,
	'64' ,
	'505' ,
	'227' ,
	'234' ,
	'683' ,
	'672' ,
	'670' ,
	'47' ,
	'968' ,
	'680' ,
	'507' ,
	'675' ,
	'595' ,
	'51' ,
	'63' ,
	'48' ,
	'351' ,
	'1787' ,
	'974' ,
	'262' ,
	'40' ,
	'7' ,
	'250' ,
	'378' ,
	'239' ,
	'966' ,
	'221' ,
	'381' ,
	'248' ,
	'232' ,
	'65' ,
	'421' ,
	'386' ,
	'677' ,
	'252' ,
	'27' ,
	'34' ,
	'94' ,
	'290' ,
	'1869' ,
	'1758' ,
	'249' ,
	'597' ,
	'268' ,
	'46' ,
	'41' ,
	'963' ,
	'886' ,
	'7' ,
	'66' ,
	'228' ,
	'676' ,
	'1868' ,
	'216' ,
	'90' ,
	'7' ,
	'993' ,
	'1649' ,
	'688' ,
	'256' ,
	'380' ,
	'971' ,
	'598' ,
	'7' ,
	'678' ,
	'379' ,
	'58' ,
	'84' ,
	'84' ,
	'84' ,
	'681' ,
	'969' ,
	'967' ,
	'260' ,
	'263' ,
    ]
    const degits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    phoneNumber+= phoneCodes[Math.floor(Math.random() * phoneCodes.length)]
    for(let i = 0; i < 9; i++) {
        phoneNumber+= degits[Math.floor(Math.random() * degits.length)] 
    }
    return phoneNumber
}
stream.once('open', function(fd) {
  for(let i = 0; i < 2000000; i++) {
   let name = gName(firstNames, lastNames)
   let gender = gGender(genders); 
   let year = gYear() 
   let status = gMaritalStatus(maritalStatus)
   let countrie = gCountries(countries)
   let language = gLanguage(languages)
   let job = gJob(jobs)
   let phoneNumber = gPhoneNumber()
   stream.write(i + "| " + "'" + name + "'" + "| " + "'" + gender + "'" + "| " + year + "| " + "'" + status + "'"  + "| " + "'"  + countrie + "'"  + "| " + "'" + language + "'"  + "| "  + "'" + job  + "'" + "| " + "'"  + phoneNumber  + "'" +  "\n")
  }
  stream.end();
});
